### ISSUE TITLE
Code and UI / UX Style Guide Associated With Project?

### ISSUE THREAD

**Issue by frankieloscavio** [reddit/reddit-mobile#104]
I am curious if we wanted to have any coding standards, ui / ux and interactivity standards associated with this project? I didn't quite know the best way to ask this question but I did find  this - https://github.com/reddit/styleguide related to the "reddit engineering style guide". As for interactivity and ui is there any over-arching vision or guide for that as well? Also I wasn't sure if you wanted to add these things to either the wiki or the readme? 

Is there an over-arching design vision for this mobile version and if so how would one who wants to contribute know what they are?

**Comment by ajacksified** [comment]
There's a lot of change right now, as we test out how people use mobile web and adapt; we don't have a complete style guide yet, but I hope to have one at some point. Maybe @Boriss can shed a little light on that process?

**Comment by milkshoes** [comment]
I'd be more than happy to help with the style guide effort for both coding and design when you want. If I might suggest the really nice open-source  SC5 living style guide as a consideration. it would be able to tie into build via gulp and npm and works with real CSS, sass and less. you could see here - http://styleguide.sc5.io/

Again I'm just happy to help you get an amazing Mobile version :)

**Comment by ajacksified** [comment]
That's pretty neat. We're currently based on bootstrap (just to get going, not sure if we're sticking with it forever); I think if we spent some effort backfilling some examples (like listings, comment lists, etc) and some of the variable changes we've made, we could start moving in that direction.

**Comment by Boriss** [comment]
@milkshoes 
Short answer: There will be one, stay tuned!
Long answer: Because we're moving as fast as we can on mobile web, we're not really pausing for style guide work at the moment.  I have some documents that I'm using to build this up as we go, and that I'll be polishing and publishing, but probably not before more development work gets done.  All of reddit - not just mobile - needs this guide, since all of our products should be similar in the ways that we find important.

**Comment by xPetrus** [comment]
I'd be willing to collaborate on styling as well!

**Comment by phil303** [comment]
Closing this as a stale issue
