### ISSUE TITLE
Microsoft Edge Support

### ISSUE THREAD

**Issue by MystK** [reddit/reddit-mobile#123]
It looks weird on Microsoft Edge. Will Edge, Microsoft's new browser, be supported?

**Comment by ajacksified** [comment]
Yup, eventually! Right now, we're focusing on cleaning up some early design iterations; once we get a solid design in place, we're going to clean up a lot of the existing bugs (and take care of some high-priority blocking bugs in the meantime.)

**Comment by phil303** [comment]
With the mweb rewrite in place, this particular issue is stale. That being said, there is an issue being tracked internally to understand how the rewrite is doing on Windows machines.
