### ISSUE TITLE
IE: Sizing of dropdown menu icon

### ISSUE THREAD

**Issue by kgram** [reddit/reddit-mobile#129]
IE11 seems to have a preference for css-size over size-attributes on svg-elements. Thus, the dropdown icon by every post on the front page gets auto-sized to 300x781px, rather than the intended 20x20px. The correct size is specified on the svg element itself, and there seems to be no reason for the auto-size specified in css.

The rules in question is found in `assets/less/components/Dropdown.less`, line 11-12

There are 2 possible fixes  (tested in debuggers of Chrome 42, Firefox 30 and  IE 11): Either remove the rules or change both from auto to 20px. If changed to 20px the size should probably be removed from the svg-tag.

**Comment by ajacksified** [comment]
Thanks! I think @danehansen is on it.

**Comment by danehansen** [comment]
Yea I just rolled that into one of my PRs I have in progress, since it was so small. It will be out soon.
