### ISSUE TITLE
NSFW placeholder "Show post?" button does nothing

### ISSUE THREAD

**Issue by miketaylr** [reddit/reddit-mobile#239]
1) visit https://m.reddit.com/r/pics/comments/3bfy7m/topless_lebanese_girls_burning_isis_flags_nsfw/
2) Click "Show post?" from blue "This post is marked as NSFW" placeholder.

Expected: The image appears
Actual: Nothing.

I see there aren't any event handlers set on that `<p class=ListingContent-nsfw-p outlined>`, so I'm not sure if this is just a UX bug or what. It would seem to me that it's a call to action.

Originally reported at https://github.com/webcompat/web-bugs/issues/1305

**Comment by miketaylr** [comment]
https://github.com/reddit/reddit-mobile/commit/c9adaf1d1ae8de08c6532cc15fe11b9bc6d38fed seems relevant.

**Comment by ajacksified** [comment]
Yup - fixed. Thanks!
