### ISSUE TITLE
In App Perf: The Submit Screen

### ISSUE THREAD

**Issue by samccone** [reddit/reddit-mobile#248]
Thanks to @paulirish for kicking this off in #247

I decided to take a dive into the in app perf and try to identify any low hanging fruit for you guys to pick off. After playing around with the mobile site for a while I started to have a hunch there was something happening with the submit screen open close flow

![screen shot 2015-07-02 at 8 50 55 pm](https://cloud.githubusercontent.com/assets/883126/8492267/313ed82c-20fc-11e5-8a94-391d92b78ed3.png)

#### Testing Process

* Visit the mobile site in chrome canary
* login 
* Open the menu once (to warm any in page cache)
* force a GC
* take a heap snapshot
* start the profiler
* open and close the menu three times
* force a GC
* stop the profiler

Lets take a look at what I uncovered

![screen shot 2015-07-02 at 8 47 18 pm](https://cloud.githubusercontent.com/assets/883126/8492283/6efc1b52-20fc-11e5-99f2-5df86fdd3b5a.png)

:memo: Note how the Node count (green line) does not go down when we force the last gc :warning: 

**it looks like we have around a 6000 Node leak per menu open close**

Alright, at this point I am pretty sure that we have run into some sort of memory leak. To further investigate I opened the profiles tab and selected the second snapshot and chose "Objects allocated between Snapshot 1 and Snapshot 2" to compare what new objects have been allocated. (mostly looking for detached nodes at this point)

![screen shot 2015-07-02 at 8 48 58 pm](https://cloud.githubusercontent.com/assets/883126/8492322/e8a767a4-20fc-11e5-9b98-8f86fb4ebddb.png)
![screen shot 2015-07-02 at 8 48 47 pm](https://cloud.githubusercontent.com/assets/883126/8492323/e8a8b2f8-20fc-11e5-9b8d-8ff62e9186ea.png)
![screen shot 2015-07-02 at 8 45 51 pm](https://cloud.githubusercontent.com/assets/883126/8492325/e8aa0a22-20fc-11e5-8e31-5358f75e82d8.png)

------------

Alright what does this show us? Well it looks like TweenLite does not want to give up its references to some divs, spans, and SVGs. The leaking node count is exacerbated by the fact that it looks like we are holding onto all of the svgs child nodes. 

Hopefully this helps you guys out, let me know if you have any questions :cactus:

**Comment by ajacksified** [comment]
Thanks! We'll investigate TweelLite.

**Comment by samccone** [comment]
@ajacksified did you have any luck tracking the leaks down?

**Comment by ajacksified** [comment]
@samccone yeah; I mean to write something up soon, but we've made some huge improvements, and more on the way. Thanks!

**Comment by samccone** [comment]
awesome! :+1:
