### ISSUE TITLE
Links from google consistently redirect to home page when on mobile app

### ISSUE THREAD

**Issue by Plasma** [reddit/reddit-mobile#430]
When searching for reddit threads via google, you get to see links like this in search results:

https://m.reddit.com/r/brownman/comments/34fhk6/is_anybody_working_on_a_compilation_of_best_of/

(This is just a random thread I found searching for jibberish)

When you click on it via Chrome in iPhone, you just get redirected to https://m.reddit.com which is obviously super frustrating.

If I click on that link now in a web browser on Chrome deskop it works, but if I reload the page it pushes me back to m.reddit.com too!

If I drop the m subdomain then the link works always: https://reddit.com/r/brownman/comments/34fhk6/is_anybody_working_on_a_compilation_of_best_of/

(Referred from https://github.com/reddit/reddit/issues/1494 )

**Comment by eridal** [comment]
This is an internal reddit problem, it's not related to the fact the user came from the an external website.

This is makes browsing reddit really annoying since you cannot navigate to any internal section. All links will trigger the home page. The only one that seems to work is the "next page"

**Comment by phil303** [comment]
This should be fixed now. Feel free to re-open if that's not the case.
