### ISSUE TITLE
EU cookie notice shouldn't move content

### ISSUE THREAD

**Issue by jomo** [reddit/reddit-mobile#503]
The EU cookie notice loads _after_ all other page content, but is inserted _at the top_, moving the rest of the page down.

This is very annoying in cases like the one shown below, where you end up hitting the wrong button:  
![reddit mobile cookie](https://i.imgur.com/SlqOL4a.gif)

May I suggest setting the `.infobar` to `position: absolute`?

![infobar absolute](https://i.imgur.com/DKwmXwg.gif)

**Comment by phil303** [comment]
This looks fixed with the rewrite.
