### ISSUE TITLE
Unable to use password with certain symbols

### ISSUE THREAD

**Issue by kevdougful** [reddit/reddit-mobile#686]
I was able to log into [reddit.com](https://www.reddit.com) on Android Chrome and Ubuntu Chrome; as well as [m.reddit.com](https://m.reddit.com) on Android Chrome but not in the official Android app (from the Play store, of course).  I was getting a `java.util.concurrent.ExecutionException: com.android.volley.AuthFailureError`

After some head scratching I decided to look at my password (I use LastPass so I have no idea what my passwords are usually) and found that it contained `*`, `%`, and `@`.  After changing my password to one that only contains [A-Za-z0-9] I was able to login on the app.

**Comment by umbrae** [comment]
Thanks for the report. This is the repo for the mobile website, but rest assured that we've got this bug triaged in house to take a look at.

**Comment by kevdougful** [comment]
Yeah, I couldn't find a repo for the android app (not open source?).  Good to hear you're working on it.  I also [posted to reddit.com](https://redd.it/4yg2tx)
