### ISSUE TITLE
NPM Install Fails

### ISSUE THREAD

**Issue by goldspin** [reddit/reddit-mobile#876]
The npm install fails.  Opened an issue below at the source, but hope it gets more attention here.
https://github.com/reddit/node-api-client/issues/175

**Comment by phil303** [comment]
@goldspin Thanks for your interest! As you may or may not be aware, we've recently switched to a new architecture, which you can find under the `2X` branch of this repo. This should be a much simpler (and working installation). Under 2X, the README needs an update but it looks mostly correct - you no longer need to do the git submodule bit, just `npm install` should set you up.

Currently all devs are focusing on fixing issues with this version but once we have some free time to think about how we want to do the git switchover from 2X to master, we'll do so.

**Comment by goldspin** [comment]
Thanks, Phil.  I had no idea about the 2X branch.  I will try it.

**Comment by goldspin** [comment]
Yes, running the 2X branch works!  But my interest also includes running it
as a docker container.  But no matter which branch I tried, I still run
into a problem where the dependency on ajacksified/snoode
<https://github.com/reddit/node-api-client/blob/master/package.json> is not
found.  Is there another branch where I can just build a simple docker
container?

  "repository": {
    "type": "git",
*    "url": "https://github.com/ajacksified/snoode.git
<https://github.com/ajacksified/snoode.git>"*
  },

**Comment by phil303** [comment]
Can you post the output from the `npm install` step? It looks like that package, which was removed as a hard dependency in the reddit-mobile repo, is still a peer dependency in `node-api-client` (which we need to remove obviously.) I believe npm will warn you that you have unmet peer deps but it shouldn't break anything.

**Comment by goldspin** [comment]
Hi Phil, here is the output from the npm install.  I am on the 2X branch,
and using the old Dockerfile (see below), which looks sane to me.


*sudo docker build -t us.gcr.io/cicd-20161022/redditmobile
<http://us.gcr.io/cicd-20161022/redditmobile> .*

Sending build context to Docker daemon 1.575 MB
Sending build context to Docker daemon
Step 0 : FROM nodesource/vivid:4.2.3
 ---> 4c5037a5abb3
Step 1 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> eeb1a44bbd32
Step 2 : RUN echo "deb-src http://archive.ubuntu.com/ubuntu trusty main" >>
/etc/apt/sources.list     && apt-get update     && apt-get install -y curl
python2.7 git     && apt-get update     && apt-get upgrade -y     &&
apt-get clean     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
 ---> Using cache
 ---> 23da6f6680f7
Step 3 : ADD package.json package.json
 ---> cbeb388eda4a
Removing intermediate container ecbefbc4ccbb
Step 4 : RUN NODE_ENV=development npm install
 ---> Running in 17b75333ed2b
npm WARN package.json r-project-blackbird@0.0.1 No repository field.
npm WARN package.json r-project-blackbird@0.0.1 No README data
npm WARN peerDependencies The peer dependency sinon@>=1.4.0 <2 included
from sinon-chai will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN peerDependencies The peer dependency js-cookie@2.1.1 included from
@r/redux-state-archiver will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN peerDependencies The peer dependency react@15.0.1 included from
@r/redux-state-archiver will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN peerDependencies The peer dependency react-dom@15.0.1 included
from @r/redux-state-archiver will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please
install the latest version of pug instead of jade
npm WARN peerDependencies The peer dependency superagent-retry@git://
github.com/ajacksified/superagent-retry#d39d7adbcd021d8ed09df440dba970c91fed9cd4
included from @r/api-client will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@2.0.3: graceful-fs v3.0.0 and before will
fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon
as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror
git://github.com/ajacksified/superagent-retry.git
/root/.npm/_git-remotes/git-github-com-ajacksified-superagent-retry-git-2878f302:
Cloning into bare repository
'/root/.npm/_git-remotes/git-github-com-ajacksified-superagent-retry-git-2878f302'...
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror
git://github.com/ajacksified/superagent-retry.git
/root/.npm/_git-remotes/git-github-com-ajacksified-superagent-retry-git-2878f302:
fatal: remote error:
npm ERR! git clone --template=/root/.npm/_git-remotes/_templates --mirror
git://github.com/ajacksified/superagent-retry.git
/root/.npm/_git-remotes/git-github-com-ajacksified-superagent-retry-git-2878f302:
  Repository not found.
npm WARN peerDependencies The peer dependency webpack@^1.9.11 included from
extract-text-webpack-plugin will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN peerDependencies The peer dependency cheerio@0.19.x || 0.20.x
included from chai-enzyme will no
npm WARN peerDependencies longer be automatically installed to fulfill the
peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend
on it explicitly.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or
higher to avoid a RegExp DoS issue
npm WARN optional dep failed, continuing fsevents@1.0.15
npm WARN optional dep failed, continuing fsevents@1.0.15
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git clone
--template=/root/.npm/_git-remotes/_templates --mirror git://
github.com/ajacksified/superagent-retry.git
/root/.npm/_git-remotes/git-github-com-ajacksified-superagent-retry-git-2878f302
npm ERR! Cloning into bare repository
'/root/.npm/_git-remotes/git-github-com-ajacksified-superagent-retry-git-2878f302'...
npm ERR! fatal: remote error:
npm ERR!   Repository not found.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
INFO[0180] The command [/bin/sh -c NODE_ENV=development npm install]
returned a non-zero code: 1



#### Dockerfile for reddit-mobile

FROM nodesource/vivid:4.2.3

ENV DEBIAN_FRONTEND noninteractive

RUN echo "deb-src http://archive.ubuntu.com/ubuntu trusty main" >>
/etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y curl python2.7 git \
    && apt-get update \
    && apt-get upgrade -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ADD package.json package.json
RUN NODE_ENV=development npm install

###### RUN npm config set registry http://registry.npmjs.org/

ADD . .
RUN npm run build

# start the server
ENTRYPOINT npm start

**Comment by phil303** [comment]
Hmm, that's a strange one to me. Just for a sanity check I removed my own local node_modules and re-ran `npm install` and am having no problems. I wonder if it's something specific to your docker setup?

The only other thing I can think of is - is there an `npm-debug.log` file and can you post its contents? Also what node and npm versions are you on? Grasping at straws a little here.

If I get a free minute on Monday, I'll remove that line from api-client since it doesn't need to be there.

**Comment by goldspin** [comment]
I was using:
FROM nodesource/vivid:4.2.3
node v4.2.3
npm  v2.14.7

But you gave me an idea, and I changed the following in the Dockerfile.
FROM node:latest
Which is using version 7, and then the build worked and run perfectly!!!!
This really makes my weekend, and I really appreciate your help!!!!!!!
It's pretty early, but I'm going to enjoy a beer.  I owe you one.  :)

**Comment by phil303** [comment]
Woot! I didn't do much but glad you figured it out.
